import type { ApplicationFormValues } from "@/features/applications/types/applicationForm";

export const EMPTY_FORM_VALUES: ApplicationFormValues = {
  company: "",
  companyWebsite: "",
  role: "",
  department: "",
  employmentType: "full_time",
  workMode: "hybrid",
  location: "",
  seniorityLevel: "",
  source: "",
  status: "saved",
  appliedDate: "",
  deadlineDate: "",
  referralName: "",
  recruiterName: "",
  recruiterEmail: "",
  salaryMin: "",
  salaryMax: "",
  salaryCurrency: "USD",
  equityOffered: false,
  priority: "medium",
  jobDescription: "",
  tags: [],
  notes: "",
  resumeFile: null,
  coverLetterFile: null,
};
