import type { Application } from "@/features/applications/types/application";

export function makeApplication(overrides: Partial<Application> = {}): Application {
  return {
    id: "app-1",
    userId: "user-1",
    company: "Acme",
    companyWebsite: null,
    role: "Frontend Engineer",
    department: null,
    employmentType: "full_time",
    workMode: "hybrid",
    location: "Cairo",
    seniorityLevel: null,
    jobPostingUrl: null,
    jobDescription: null,
    status: "applied",
    appliedDate: "2026-03-10",
    deadlineDate: null,
    source: "linkedin",
    referralName: null,
    recruiterName: null,
    recruiterTitle: null,
    recruiterEmail: null,
    recruiterPhone: null,
    priority: "medium",
    salaryMin: null,
    salaryMax: null,
    salaryCurrency: "USD",
    equityOffered: false,
    offerDeadline: null,
    contactEmail: null,
    tags: [],
    notes: null,
    rejectionReason: null,
    hasResume: false,
    resumeFileName: null,
    hasCoverLetter: false,
    coverLetterFileName: null,
    archived: false,
    nextRound: null,
    createdAt: "2026-03-10T00:00:00.000Z",
    updatedAt: "2026-03-10T00:00:00.000Z",
    ...overrides,
  };
}
